Jobs ava to mocha
nareshqlogic/nodejs-docs-samples pull request #3
Opened 2019-02-05 15:31 UTC by nareshqlogic

2019-02-12 19:18 UTC, romlogic commented on jobs/v3/system-test/basic-job-sample.test.js
> +it(`Should create a job, get a job, update a job, update a job with field mask and delete a job`, async () => {
This should have a serial coma i.e. '...update a job with field mask, and delete a job' but if the line has to be like this verbatim, you can ignore.

2019-02-15 15:12 UTC, ajaaym requested changes
Fix backtick issue and after that create public PR

2019-02-15 15:12 UTC, ajaaym commented on jobs/v3/system-test/auto-complete-sample.test.js
>  const tools = require(`@google-cloud/nodejs-repo-tools`);
There are still backquote on both of above two lines.

2019-02-15 15:12 UTC, ajaaym commented on jobs/v3/system-test/auto-complete-sample.test.js
> +it(`should auto complete job titles within given companyName`, async () => {
back tick instead of quote.

2019-02-15 15:12 UTC, ajaaym commented on jobs/v3/system-test/auto-complete-sample.test.js
>    const output = await tools.runAsync(`node auto-complete-sample.js`);
still back tick here.

2019-02-15 18:01 UTC, closed without merging