Iot ava to mocha
nareshqlogic/nodejs-docs-samples pull request #5
Opened 2019-02-11 11:46 UTC by nareshqlogic

2019-02-13 10:36 UTC, praveenqlogic commented on iot/mqtt_example/system-test/cloudiot_mqtt_example.test.js
>    return topic.delete().then(() => {
use await!

2019-02-13 10:37 UTC, praveenqlogic commented on iot/mqtt_example/system-test/cloudiot_mqtt_example.test.js
>    return pubsub.createTopic(topicName).then(results => {
use await!

2019-02-13 10:40 UTC, praveenqlogic commented on iot/beta-features/gateway/gateway.test.js
>    let pubsubRes = await pubsub.createTopic(topicName);
const [topic] = await pubsub.createTopic(topicName); // can be use

2019-02-15 15:21 UTC, ajaaym requested changes
small nit

2019-02-15 15:21 UTC, ajaaym commented on iot/http_example/system-test/cloudiot_http_example.test.js
> +it('should send event messagei', async () => {
extra i in message

2019-02-15 18:31 UTC, closed without merging